### ISSUE TITLE
Archivo -> clientes 

### ISSUE THREAD

**Issue by ivantrujillo79** [TransformaTI/CyC#11]
# ------ESPECIFICACIONES------

## Requisitos:
- La implementación del requerimiento será en la librería SigametClasses del repositorio SigametLibrerias

![image.png](https://images.zenhubusercontent.com/59a050988f62dc7798c4133f/41835832-c204-4e5d-b16a-8f929df19404)

## Procedimiento
1. Descargar la versión más reciente de la rama **development**
2. Crear una rama de tipo **Feature** a partir de la rama **development**
3. Abrir el formulario **ConsultaCliente.vb** 
4. Crear un miembro privado de tipo String llamado _URLGateway y cargarlo en el constructor del formulario
5. Sobrecargar el método **Consulta** para que acepte un parámetro adicional llamada **URLGateway** y consultar los datos del cliente por medio de una nueva instancia del RTGMGateway

## Criterios de aceptación:
i) Los datos deberán ser consultados desde el web service de haber un parámetro válido
ii) Los datos deberán ser consultados desde la base de datos SIGAMET de NO haber parámetro URLGateway

**Comment by Ruben-1** [comment]
Rama: RM_Feature_ConsultaCliente_20_03_2018
