### ISSUE TITLE
Inactivar Autorización de crédito

### ISSUE THREAD

**Issue by ivantrujillo79** [TransformaTI/CyC#17]
# ------ESPECIFICACIONES------

## Requisitos:
- Ajuste que será realizado directamente en el módulo de crédito y cobranza
- Inactivar la opción Autorización de Crédito

![image](https://user-images.githubusercontent.com/30910881/37678751-8e3d2ac8-2c44-11e8-82c1-d203ef61f7f2.png)

## Procedimiento
1. Descargar la versión más reciente de la rama **development**
2. Crear una rama de tipo **Feature** a partir de la rama **development**
3. Consultar el valor del parámetro URLGateway
 a) Sí el valor es vacío, nulo o inexistente habilitar la opción del menú **Archivo -> Autorización de Crédito**
 b) Sí el valor es válido **inhabilitar** la opción del menú **Archivo -> Autorización de Crédito**

## Criterios de aceptación:
i) Que la opción Archivo -> Autorización de Crédito sea visible si no hay parámetro
ii) Que la opción Archivo -> Autorización de Crédito sea invisible si hay un valor adecuado para el parámetro

**Comment by Ruben-1** [comment]
Rama: RM_Feature_InactivarAutorizacionCredito_26_03_2018
