### ISSUE TITLE
Req. 37 Inactivar Menú Catalogo - > Clientes con Descuento

### ISSUE THREAD

**Issue by ivantrujillo79** [TransformaTI/CyC#28]
# ------ESPECIFICACIONES------

## Requisitos:
- Ajuste que será realizado directamente en el módulo de crédito y cobranza
- Inactivar la opción Menú Catalogo - > Clientes con Descuento

![image](https://user-images.githubusercontent.com/30910881/37688492-0bc0279a-2c66-11e8-99f9-e981ae71ae1a.png)

## Procedimiento
1. Descargar la versión más reciente de la rama **development**
2. Crear una rama de tipo **Feature** a partir de la rama **development**
3. Consultar el valor del parámetro URLGateway
 a) Sí el valor es vacío, nulo o inexistente habilitar la opción del menú **Menú Catalogo - > Clientes con Descuento**
 b) Sí el valor es válido **inhabilitar** la opción del menú **Menú Catalogo - > Clientes con Descuento**

## Criterios de aceptación:
i) Que la opción Menú Catalogo - > Clientes con Descuento sea visible si no hay parámetro
ii) Que la opción Menú Catalogo - > Clientes con Descuento sea invisible si hay un valor adecuado para el parámetro

**Comment by Ruben-1** [comment]
Rama: RM_Feature_InactivarAutorizacionCredito_26_03_2018
