### ISSUE TITLE
Req. 38 Inactivar Menú Catalogo - > Asignación de Ejecutivos Responsables

### ISSUE THREAD

**Issue by ivantrujillo79** [TransformaTI/CyC#29]
# ------ESPECIFICACIONES------

## Requisitos:
- Ajuste que será realizado directamente en el módulo de crédito y cobranza
- Inactivar la opción Menú Catalogo - > Asignación de Ejecutivos Responsables

![image](https://user-images.githubusercontent.com/30910881/37688549-479cf5d6-2c66-11e8-8b15-b3769d12d58d.png)

## Procedimiento
1. Descargar la versión más reciente de la rama **development**
2. Crear una rama de tipo **Feature** a partir de la rama **development**
3. Consultar el valor del parámetro URLGateway
 a) Sí el valor es vacío, nulo o inexistente habilitar la opción del menú **Menú Catalogo - > Asignación de Ejecutivos Responsables**
 b) Sí el valor es válido **inhabilitar** la opción del menú **Menú Catalogo - > Asignación de Ejecutivos Responsables**

## Criterios de aceptación:
i) Que la opción Menú Catalogo - > Asignación de Ejecutivos Responsables sea visible si no hay parámetro
ii) Que la opción Menú Catalogo - > Asignación de Ejecutivos Responsables sea invisible si hay un valor adecuado para el parámetro

**Comment by Ruben-1** [comment]
Rama: RM_Feature_InactivarAutorizacionCredito_26_03_2018
