### ISSUE TITLE
Req. 40 Inactivar Menú Herramientas -> buró de Crédito

### ISSUE THREAD

**Issue by ivantrujillo79** [TransformaTI/CyC#30]
# ------ESPECIFICACIONES------

## Requisitos:
- Ajuste que será realizado directamente en el módulo de crédito y cobranza
- Inactivar la opción Menú Herramientas -> buró de Crédito

![image](https://user-images.githubusercontent.com/30910881/37688597-800b4080-2c66-11e8-8583-333504bdb176.png)

## Procedimiento
1. Descargar la versión más reciente de la rama **development**
2. Crear una rama de tipo **Feature** a partir de la rama **development**
3. Consultar el valor del parámetro URLGateway
 a) Sí el valor es vacío, nulo o inexistente habilitar la opción del menú **Menú Herramientas -> buró de Crédito**
 b) Sí el valor es válido **inhabilitar** la opción del menú **Menú Herramientas -> buró de Crédito**

## Criterios de aceptación:
i) Que la opción Menú Herramientas -> buró de Crédito sea visible si no hay parámetro
ii) Que la opción Menú Herramientas -> buró de Crédito sea invisible si hay un valor adecuado para el parámetro

**Comment by Ruben-1** [comment]
Rama: RM_Feature_InactivarAutorizacionCredito_26_03_2018
