### ISSUE TITLE
Pantalla ConsultaCargo SIGAMETCLASSES

### ISSUE THREAD

**Issue by ivantrujillo79** [TransformaTI/CyC#4]
# ------ESPECIFICACIONES------

## Requisitos:
-El cambio será realizado en el repositorio de SigametLibrerias, en el proyecto SigaMetClasses
-Asegurar que en su ambiente las referencias al componente RTGMGateway se encuentran configuradas correctamente

![image](https://user-images.githubusercontent.com/30910881/37539161-98a089c6-2918-11e8-8408-f4627b5bfe77.png)

## Procedimiento
1. Descargar la versión más reciente de la rama **development**
2. Crear una rama de tipo **Feature** a partir de la rama **development**
3. Asegurar que se tiene la última versión de la DLL RTGMGateway referenciada al proyecto SigaMetClasses
4. Ubicar el módulo **ConsultaCargo.vb**
5. Crear un miembro privado de tipo String llamado _URLGateway y cargarlo en el constructor del formulario
6. Crear una sobrecarga del método **ConsultaDocumento** para que solicite un nuevo parámetro de tipo String llamado **URLGateway**, en la implementación se llamará al método **RTGMPedidoGateway.buscarPedidos** y se tomará la respuesta para cargar el valor de los controles del formulario siguientes:
lblPedido.Text
lblAnoPed.Text
lblTipoDocumento.Text 
lblStatusPedido.Text  
lblStatusCobranza.Text
lblCliente.Text       
lblRutaSuministro.Text
lblFCargo.Text
lblImporte.Text
lblSaldo.Text
7. En el controlador del evento clic del botón **btnBuscar** (btnBuscar_Click)  incluir una sentencia IF para verificar que exista una URL configurada para el módulo y se comporte así:
 a) Sí no hay URL utilizar el método ConsultaDocumento **no sobrecargado**
 b) Sí hay URL utilizar el método ConsultaDocumento **sobrecargado**

## Criterios de aceptación:
i) Que la pantalla funcione sin generar errores en ausencia del parámetro URLGateway
ii) Que la pantalla funcione sin generar errores en ausencia de valor para el parámetro URLGateway
ii) Que la pantalla funcione sin generar errores con valor inválido para el parámetro URLGateway

**Comment by bserrano0215** [comment]
COMENTARIO DE PRUEBA
